# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fibonacci.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fibonacci.proto',
  package='Fibonacci',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x66ibonacci.proto\x12\tFibonacci\"\x1c\n\nFibRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1d\n\x0b\x46ibResponse\x12\x0e\n\x06number\x18\x01 \x01(\t2]\n\x11\x46ibonacciComputer\x12H\n\x15GetNthFibonacciNumber\x12\x15.Fibonacci.FibRequest\x1a\x16.Fibonacci.FibResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FIBREQUEST = _descriptor.Descriptor(
  name='FibRequest',
  full_name='Fibonacci.FibRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Fibonacci.FibRequest.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_FIBRESPONSE = _descriptor.Descriptor(
  name='FibResponse',
  full_name='Fibonacci.FibResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Fibonacci.FibResponse.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['FibRequest'] = _FIBREQUEST
DESCRIPTOR.message_types_by_name['FibResponse'] = _FIBRESPONSE

FibRequest = _reflection.GeneratedProtocolMessageType('FibRequest', (_message.Message,), dict(
  DESCRIPTOR = _FIBREQUEST,
  __module__ = 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:Fibonacci.FibRequest)
  ))
_sym_db.RegisterMessage(FibRequest)

FibResponse = _reflection.GeneratedProtocolMessageType('FibResponse', (_message.Message,), dict(
  DESCRIPTOR = _FIBRESPONSE,
  __module__ = 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:Fibonacci.FibResponse)
  ))
_sym_db.RegisterMessage(FibResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class FibonacciComputerStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetNthFibonacciNumber = channel.unary_unary(
          '/Fibonacci.FibonacciComputer/GetNthFibonacciNumber',
          request_serializer=FibRequest.SerializeToString,
          response_deserializer=FibResponse.FromString,
          )


  class FibonacciComputerServicer(object):

    def GetNthFibonacciNumber(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_FibonacciComputerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetNthFibonacciNumber': grpc.unary_unary_rpc_method_handler(
            servicer.GetNthFibonacciNumber,
            request_deserializer=FibRequest.FromString,
            response_serializer=FibResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Fibonacci.FibonacciComputer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaFibonacciComputerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetNthFibonacciNumber(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaFibonacciComputerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetNthFibonacciNumber(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetNthFibonacciNumber.future = None


  def beta_create_FibonacciComputer_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Fibonacci.FibonacciComputer', 'GetNthFibonacciNumber'): FibRequest.FromString,
    }
    response_serializers = {
      ('Fibonacci.FibonacciComputer', 'GetNthFibonacciNumber'): FibResponse.SerializeToString,
    }
    method_implementations = {
      ('Fibonacci.FibonacciComputer', 'GetNthFibonacciNumber'): face_utilities.unary_unary_inline(servicer.GetNthFibonacciNumber),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_FibonacciComputer_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Fibonacci.FibonacciComputer', 'GetNthFibonacciNumber'): FibRequest.SerializeToString,
    }
    response_deserializers = {
      ('Fibonacci.FibonacciComputer', 'GetNthFibonacciNumber'): FibResponse.FromString,
    }
    cardinalities = {
      'GetNthFibonacciNumber': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Fibonacci.FibonacciComputer', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
